

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjetoDA
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Model1Container : DbContext
{
    public Model1Container()
        : base("name=Model1Container")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Casa> Casa { get; set; }

    public virtual DbSet<Arrendamento> ArrendamentoSet { get; set; }

    public virtual DbSet<Limpeza> Limpeza { get; set; }

    public virtual DbSet<Servico> Servico { get; set; }

    public virtual DbSet<Venda> Venda { get; set; }

}

}

